config/routes.rb
Voyager::Application.routes.draw do
  mount Forem::Engine, :at => "/forums"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  match "oauth/callback" => "oauths#callback"

  resources :messages do
    collection do
      get :outbox
    end
  end
  resources :password_resets
  resources :users do
    member do
      get :activate
    end
  end

  resources :sessions

  get "login" => "sessions#new", :as => :login
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => :signup

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    #can [:new, :create, :activate], User, 
    
    user ||= User.new # guest user (not logged in)
    #if user #.admin?
    #  can :create
    #end
    #  can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
  acts_as_messageable

  attr_accessible :username, :password, :password_confirmation,
    :email, :remember_me, :authentications_attributes
  validates_confirmation_of :password

  validates :username, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  helper_method :forem_user

  protect_from_forgery
  
  # next, for user and admin controllers put in it filter,
  # and remove from controller visible for guest
  before_filter :require_login
    
  helper_method :current_users_list

  #######################
  protected
  
  def current_users_list
    current_users.map { |u| u.username }.join(", ")
  end
  
  # protected
  def not_authenticated
    redirect_to login_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login
  
  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = current_user.received_messages
  end

  def outbox
    @messages = current_user.sent_messages
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @message = current_user.messages.with_id(params[:id]).first
    if @message.destroy
      flash[:notice] = "All ok"
    else
      flash[:error] = "Fail"
    end
    redirect_to messages_path
  end

  def new
    @message = ActsAsMessageable::Message.new
  end

  def create
    @to = User.find_by_email(params[:message][:to])
    if @to
      current_user.send_message(@to, params[:message][:topic], params[:message][:body])
      redirect_to root_url
    else
      flash[:error] = "Wrong email!"
      redirect_to new_message_path
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login
  
  def oauth
    login_at(params[:provider])
  end
  
  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice =>  "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failer to login from #{provider.titleize}!"
      end
    end
  end


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
  
  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_reset_password_instructions! 
      redirect_to root_path, :notice => "Instructions have been sent to your email."
    else
      redirect_to root_path, :notice => "User not found." #'Instructions have been sent to your email.' #"User not found."
    end
  end
  
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]
    not_authenticated if !@user
  end

  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if !@user
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      redirect_to root_path, :notice => "Password was successfully updated."
    else
      render :action => "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_path, :notice => "Logged in!"
    else
      flash[:notice] = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # load_and_authorize_resource
  skip_before_filter :require_login

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if verify_recaptcha(:model => @user, :message => "It's error with reCAPTCHA!") and @user.save
      redirect_to root_path, :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes!(params[:user])
      redirect_to edit_user_path(params[:id]), :notice => "Parameters update."
    else
      render :action => 'edit'
    end
  end
  
  def activate
    @user = User.load_from_activation_token(params[:id])
    if @user
      @user.activate!
      redirect_to login_path, :notice => 'User was successfully activated.'
    else
      not_authenticated
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Voyager
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      .container
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}", :class=>"alert-message error"
        - if current_user
          Logged in as #{current_user.email}

        %br
        %nav.signup
          - if current_user
            = link_to "Log out", main_app.logout_path
            |
            = link_to "Profile", main_app.edit_user_path(current_user)
            |
            = link_to "Inbox", main_app.messages_path
          - else
            = link_to "Sign up", main_app.signup_path
            |
            = link_to "Log in", main_app.login_path
            %br
            = link_to 'Login with Twitter', auth_at_provider_path(:provider => :twitter)
        %br

        %nav.navigation
          = link_to "Home", root_path
          |
          = link_to "Users", main_app.users_path
          |
          = link_to "Forum", main_app.forem_path
    .main
      .container
        Main
        = yield

    %footer
      .container
        Currently active users: #{current_users_list}

app/views/messages/_message.html.haml
= message.topic
by
= message.from.username
= message.body
= time_ago_in_words(message.created_at)
-# = link_to "Mark as read", mark_message_path(message.id)
= link_to "Delete", message_path(message.id), :method => :delete

app/views/messages/index.html.haml
= link_to t(:new_message), new_message_path
= link_to t(:outbox), outbox_messages_path
= render :partial => "message", :collection => @messages

app/views/messages/new.html.haml
= simple_form_for :message, :url => messages_path, :method => :post do |f|
  = f.input :to
  = f.input :topic
  = f.input :body
  = f.button :submit, "Send Message"

app/views/messages/outbox.html.haml
= render :partial => "message", :collection => @messages

app/views/messages/show.html.haml
Last sent messages[
= @user.sent_messages.size
]:
- @user.sent_messages.each do |message|
  = message.topic
  %br

app/views/oauths/callback.html.haml
%h1 Oauths#callback
%p Find me in app/views/oauths/callback.html.haml

app/views/oauths/oauth.html.haml
%h1 Oauths#oauth
%p Find me in app/views/oauths/oauth.html.haml

app/views/password_resets/edit.html.haml
%h1 Reset password

= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f|
  - if @user.errors.any?
    .error_explanation
      %h2 #{pluralize(@user.errors.count, "error")} prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg


  .field
    = f.label :email 
    = @user.email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation 
  = hidden_field_tag :token, @token
  .actions
  = f.submit

%hr

= simple_form_for @user do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.hidden_field :token, :value => @token
  = f.button :submit

app/views/users/edit.html.haml
%h1 Edit profile

= simple_form_for @user do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.button :submit, "Save"

app/views/users/index.html.haml
%h1 Users

%ul
  - @users.each do |u|
    %li= link_to u.username, user_path(u)

app/views/users/new.html.haml
= simple_form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message

  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = recaptcha_tags
  = f.button :submit, "Create new user"

app/views/users/show.html.haml
%h3= @user.username

%p= @user.email